targets:
  $default:
    sources:
      - openapi_definitions/**
      - $package$
      - lib/$lib$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "openapi_definitions"
          output_folder: "lib/generated/api_client"
