extends: ["spectral:oas"]

functionsDir: "./spectral_functions"
functions:
  - schema-type-and-format

rules:
  oas2-api-host: false
  oas2-api-schemes: false
  info-contact: false
  operation-description: false
  operation-operationId: false
  operation-tags: false

  # Taken from https://github.com/Azure/azure-api-style-guide/blob/8d7dbbd9af00b602259108a9c89c07c8e8032c3f/spectral.yaml#L627C3-L627C28.
  az-schema-type-and-format:
    description: Schema should use well-defined type and format.
    message: "{{error}}"
    severity: error
    formats: ["oas2"]
    given:
      - $.paths[*].[put,post,patch].parameters.[?(@.in == 'body')].schema
      - $.paths[*].[get,put,post,patch,delete].responses[*].schema
    then:
      function: schema-type-and-format

  # Taken from https://github.com/Azure/azure-api-style-guide/blob/8d7dbbd9af00b602259108a9c89c07c8e8032c3f/spectral.yaml#L529C3-L529C19.
  az-property-type:
    description: All schema properties should have a defined type.
    message: Property should have a defined type.
    severity: error
    resolved: false
    # Exclude properties that contains allOf or oneOf or anyOf to avoid false positives.
    given: $..properties[?(@object() && @.$ref == undefined && @.allOf == undefined && @.oneOf == undefined && @.anyOf == undefined)]
    then:
      field: type
      function: truthy

  # Taken from https://github.com/Azure/azure-api-style-guide/blob/8d7dbbd9af00b602259108a9c89c07c8e8032c3f/spectral.yaml#L237C3-L237C25.
  az-lro-response-schema:
    description: A 202 response should include a schema for the operation status monitor.
    message: A 202 response should include a schema for the operation status monitor.
    severity: error
    given: $.paths[*][*].responses[?(@property == '202')]
    then:
      field: schema
      function: truthy

  # Taken from https://github.com/Azure/azure-api-style-guide/blob/8d7dbbd9af00b602259108a9c89c07c8e8032c3f/spectral.yaml#L685.
  az-success-response-body:
    description: All success responses except 204 should define a response body.
    severity: error
    # list http methods explicitly to exclude head
    # exclude 202 to avoid duplication with az-lro-response-schema rule
    given: $.paths[*][get,put,post,patch,delete].responses[?(@property >= 200 && @property < 300 && @property != '202' && @property != '204')]
    then:
      field: schema
      function: truthy
